TaskBoard/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from .views import SignUpView, ThankYouView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('thank-you/', ThankYouView.as_view(), name='thank_you'),
]

task/urls.py
from django.urls import path, include
from .views import TaskListView, TaskCreateView, TaskDeleteView, TaskUpdateView

app_name = 'task'

urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('add-note/', TaskCreateView.as_view(), name='create_task'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='delete_task'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='update_task'),
]

task/models.py
from django.db import models
from django.contrib.auth import get_user_model, get_user


class Task(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(max_length=1000)
    date = models.DateField(auto_now=False, auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

TaskBoard/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, TemplateView


class SignUpView(CreateView):
    model = get_user_model()
    form_class = UserCreationForm
    success_url = '/thank-you/'


class ThankYouView(TemplateView):
    template_name = 'thank_you.html'

task/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Task


@method_decorator(login_required, name='dispatch')
class TaskListView(ListView):
    model = Task

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class TaskCreateView(CreateView):
    model = Task
    fields = ['title', 'description']
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('task:task_list')


@method_decorator(login_required, name='dispatch')
class TaskUpdateView(UpdateView):
    model = Task
    fields = ['title', 'description']
    success_url = '/'
    template_name_suffix = '_update_form'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Board</title>
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style></style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container-fluid main-container" style="background-image: url('{% static 'img/dark_wood.png' %}'); color: white; min-height: 100vh">
        {% block content%}

        {% endblock %}
    </div>

    <script src="https://use.fontawesome.com/7d70462258.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'task:task_list' %}">Task Board</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'task:create_task' %}">Add note <i class="fa fa-plus-square" aria-hidden="true"></i> <span class="sr-only">(current)</span></a>
            {% endif %}
        </li>
        <li class="nav-item">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'task:logout' %}">Logout <i class="fa fa-sign-out" aria-hidden="true"></i></a>
            {% else %}
                <a class="nav-link" href="{% url 'sign_up' %}">Sign Up <i class="fa fa-user-plus" aria-hidden="true"></i></a>
            {% endif %}
        </li>
      </ul>

      {% if user.is_authenticated %}
          <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
          </form>
      {% endif %}
  </div>
</nav>

templates/task/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <h4>Are you sure you want to delete note {{ object.title }}?</h4>
        <input type="submit" value="Delete">
        <a href="{% url 'task:task_list' %}">Cancel</a>
    </form>
{% endblock %}

templates/task/task_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="padding: 5%;">
        <h2 style="color: #077bff">Create your note</h2>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

templates/task/task_list.html
{% extends 'base.html' %}

{% block content %}
    {% for task in task_list %}
        <div class="task-div" style="background-color: rgba(52, 58, 64, 0.6); float: left; padding: 2%; margin: 2%; max-width: 28%;">
            <h2 style="border-left: 3px solid #007bff; padding-left: 3%">{{ task.title }}</h2>
            <br>
            <p style="font-family: 'Gloria Hallelujah', cursive;">{{ task.description }}</p>
            <p style="">{{ task.remark.text }}</p>
            <p style="float: right">{{ task.date }}</p>
            <a href="{% url 'task:delete_task' pk=task.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
            <a href="{% url 'task:update_task' pk=task.pk %}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
        </div>
    {% endfor %}
{% endblock %}

templates/task/task_update_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <h4>"{{ object.title }}" update:</h4>
        {% bootstrap_form form %}
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

templates/thank_you.html
{% extends 'base.html' %}

{% block content %}
    <div style="display: flex; justify-content: center; align-items: center;">
        <div style="width: 30%; background-color: rgba(52, 58, 64, 0.6); padding: 2%; margin-top: 15%">
            <h3>Thank you for registration!</h3>
            <h4>Please <a href="{% url 'task:login' %}">Log In</a></h4>
        </div>
    </div>
{% endblock %}